"""add growth perk choice

Revision ID: 2190a35c174f
Revises: 6b3f59d0ef66
Create Date: 2026-08-18 15:11:15.004849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2190a35c174f'
down_revision: Union[str, Sequence[str], None] = '6b3f59d0ef66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patreon_links', sa.Column('growth_perk_choice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patreon_links', 'growth_perk_choice')
    # ### end Alembic commands ###
