"""add patreon links

Revision ID: 6b3f59d0ef66
Revises: 44f8f54cbf0b
Create Date: 2026-08-18 01:59:26.854816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3f59d0ef66'
down_revision: Union[str, Sequence[str], None] = '44f8f54cbf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patreon_links',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('patreon_user_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discord_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('discord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patreon_links')
    # ### end Alembic commands ###
